from datetime import timedelta

MIN_DONOR_AGE = 18

DONATION_COOLDOWN_DAYS = 90
REQUEST_COOLDOWN_DAYS = 7
CLEANUP_AFTER_DAYS = 30

DONATION_COOLDOWN = timedelta(days=DONATION_COOLDOWN_DAYS)
REQUEST_COOLDOWN = timedelta(days=REQUEST_COOLDOWN_DAYS)